name = "mochiaibox"
main = "index.js"
compatibility_date = "2025-05-30"

[vars]
GEMINI_MODEL = "gemini-2.5-flash"

[[kv_namespaces]]
binding = "MOCHI_MEMORY"
id = "c40b7620e3ed45f19331e315bad1dd3b"

[[d1_databases]]
binding = "DB"
database_name = "mochi_db"
database_id = "12d639b2-1445-42f6-b4c0-0fd1012987d4"
